name: "Applies the migrations to the database"

on:
  push:
    branches:
      - main
      - production
      - frank/version-control-ecs-task-definitions
    paths:
      - "moped-database/**"
      - ".github/workflows/migrations-metadata-deployment.yml"
      - ".github/workflows/migrations-metadata-deployment-helper.sh"

jobs:
  apply-migrations-and-metadata:
    name: Apply Migrations and Metadata
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@v4
        name: "Setup Python"
        with:
          python-version: "3.8"
          architecture: "x64"
      # Get the code first
      - name: "Checkout Code"
        uses: actions/checkout@v3
      # Then install the AWC CLI tools & boto3
      - name: "Install AWS Cli & Hasura CLI"
        run: |
          sudo apt-get install python3-setuptools
          pip3 install awscli virtualenv
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      # Run the shell commands using the AWS environment variables
      - name: "Apply Migrations and Metadata"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_MOPED_HASURA_CONFIGURATION_FILE_PRODUCTION: ${{ secrets.AWS_MOPED_HASURA_CONFIGURAITON_FILE_PRODUCTION }}
          AWS_MOPED_HASURA_CONFIGURATION_FILE_STAGING: ${{ secrets.AWS_MOPED_HASURA_CONFIGURAITON_FILE_STAGING }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          source $(pwd)/.github/workflows/migrations-metadata-deployment-helper.sh
          # run_migration_process

  update-ecs-task-deployment:
    name: Check for updated ECS task definition and deploy if needed
    runs-on: ubuntu-24.04
    needs: apply-migrations-and-metadata
    if: always()
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Install AWS CLI v2"
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: "Validate ECS task definition"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          source $(pwd)/.github/workflows/migrations-metadata-deployment-helper.sh
          update_ecs_task_definition_process
